apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    dt.owner: label-team

---

#apiVersion: v1
#kind: LimitRange
#metadata:
#  name: mem-limitlrange
#  namespace: devnone
#spec:
#  limits:
#    - default:
#       memory: 512Mi
#      defaultRequest:
#        memory: 512Mi
#      type: Container
    

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextstore-app
  namespace: dev
  labels:
    app: nextstore
    tier: dev
    dt.owner: label-team
spec:
  selector:
    matchLabels:
      app: nextstore
      dep: DOD   
  replicas: 1
  template:
    metadata:
      name: nextstore-app
      annotations: 
        nextstore.com/owner: "Sean Mattis"
        nextstore.com/email: "sean.mattis@dynatrace.com"
        nextstore.com/department: "DOD"
      labels:
        app: nextstore 
        dep: DOD  
        dt.owner: label-team
    spec:    
      containers:
        - name: nextstore-app
          image: seanmattisdocker/nextstore:oa-js-v1
          ports:
            - containerPort: 80
          command: []
          args: ["--color","yellow"]
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: ns-cm
          volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
          

---

apiVersion: v1
kind: Service
metadata:
  name: nextstore-service
  namespace: dev
  labels:
    app: nextstore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
      app: nextstore 
      dep: DOD  

---

apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: dev
spec:
  selector:
    app: tomcat
    dep: DOD
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
